# Generated by Django 5.0 on 2023-12-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagetst.home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='header_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='images',
            field=models.ImageField(null=True, upload_to='slide_img'),
        ),
    ]
