# Generated by Django 5.0 on 2023-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0002_slide_header_alter_home_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='description',
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
