# Generated by Django 5.0 on 2023-12-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0004_houseboat_packages_alter_slide_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseboat',
            old_name='houseBoattype',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
