# Generated by Django 5.0 on 2023-12-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0007_remove_houseboat_menu_remove_packages_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_time',
        ),
        migrations.AddField(
            model_name='houseboat',
            name='menu_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='menu',
            field=models.ManyToManyField(to='imagetst.menu'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='menu',
            field=models.ManyToManyField(to='imagetst.menu'),
        ),
    ]
