# Generated by Django 5.0 on 2023-12-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0008_remove_menu_menu_time_houseboat_menu_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='menu_content',
        ),
    ]
