# Generated by Django 5.0 on 2023-12-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0010_rename_menu_content_menu_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='houseboat',
            name='menu',
        ),
        migrations.AddField(
            model_name='houseboat',
            name='menu_time',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='houseboat',
            name='menu',
            field=models.TextField(null=True),
        ),
    ]
