# Generated by Django 5.0 on 2023-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0011_remove_packages_menu_remove_houseboat_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_time', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='houseboat',
            name='menu_time',
        ),
    ]
