# Generated by Django 5.0 on 2023-12-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0012_menu_remove_houseboat_menu_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseboat',
            name='menu_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagetst.menu'),
        ),
    ]
