# Generated by Django 5.0 on 2023-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0013_houseboat_menu_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseboat',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='houseboat',
            name='menu_time',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.TextField(null=True),
        ),
    ]
