# Generated by Django 5.0 on 2023-12-24 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0016_rename_hotel_book_houseboat_book_package_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BoatBooking',
        ),
        migrations.RenameModel(
            old_name='Home',
            new_name='Heading',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
    ]
