# Generated by Django 5.0 on 2023-12-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0017_rename_book_boatbooking_rename_home_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseboat',
            name='main_des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='main_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
