# Generated by Django 5.0 on 2023-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0018_houseboat_main_des_package_main_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseboat',
            name='about_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseboat',
            name='quick_facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='about_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='quick_facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
