# Generated by Django 5.0 on 2023-12-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0019_houseboat_about_destination_houseboat_quick_facts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatbooking',
            name='user',
        ),
    ]
