# Generated by Django 5.0 on 2024-02-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0025_packagereview_delete_post_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereview',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
