# Generated by Django 5.0 on 2024-02-07 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0026_packagereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='imagetst.package'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
