# Generated by Django 5.0 on 2024-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0027_alter_packagereview_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
