# Generated by Django 5.0 on 2024-02-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0028_alter_packagereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
    ]
