# Generated by Django 5.0 on 2024-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0029_alter_packagereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
