# Generated by Django 5.0 on 2024-02-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetst', '0031_alter_packagereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseboat',
            name='title',
            field=models.CharField(choices=[('Three Bedroom Premium', 'Three Bedroom Premium'), ('Two Bedroom Premium', 'Two Bedroom Premium'), ('One Bedroom Premium', 'One Bedroom Premium'), ('Three Bedroom Deluxe', 'Three Bedroom Deluxe'), ('Two Bedroom Deluxe', 'Two Bedroom Deluxe'), ('One Bedroom Deluxe', 'One Bedroom Deluxe')], max_length=150),
        ),
    ]
